### ISSUE TITLE
Editor hint when saving content that has been published already

### ISSUE THREAD

**Issue by jamietopp21** [brudil/jetpath#26]

**Comment by brudil** [comment]
Is there a reason this needs to be permanent and not behind the Workflow tab. The reason it's under a separate tab is a lot of the time there are issues to publishing - things that need doing first. Publish to me seems to be a momentous enough occasion to go to Workflow for.

Thoughts.

**Comment by jamietopp21** [comment]
Purely for the purposes of tweaking after the first publication, the first publication should be made from the workflow tab, after that I think an easier to access publish button might be useful for quick changes!

**Comment by brudil** [comment]
Ahh, right. That's a good shout. Certainly a least some indicator that the
current version isn't the published version. Cheers

**Comment by brudil** [comment]
Added as Editor Hint notification.

<img width="358" alt="screen shot 2017-10-03 at 10 41 31" src="https://user-images.githubusercontent.com/382352/31119057-9eb21c98-a827-11e7-909a-c4fac090689e.png">
