### ISSUE TITLE
Add ability to credit articles to author of any name, instead of just pre-existing names

### ISSUE THREAD

**Issue by jamietopp21** [brudil/jetpath#28]

**Comment by brudil** [comment]
Could you explain this one a bit more?

**Comment by jamietopp21** [comment]
Sure, when writing an article you have to chose an author, you can only select from a list of 3 pre-existing ones, but it would be nice to be able to use a custom name each time if desired, for example if Stephen Weybridge is going to write in a certain style or about certain things, I'll need a different name for articles not in that category

**Comment by brudil** [comment]
Right - so being able to create authors would suit you just fine? You aren't requesting some sort of text box for 'non authors'?

**Comment by jamietopp21** [comment]
Allowing anyone to create authors would be just fine, as long as it's possible to credit an article to a new author easily!

**Comment by brudil** [comment]
Yeah it is easy enough.
